uto je: 0
KW double je: 0
KW int je: 17
KW switch je: 4
KW _Bool je: 0
KW else je: 36
KW long je: 0
KW typedef je: 0
KW break je: 0
KW enum je: 0
KW register je: 0
KW union je: 0
KW case je: 49
KW extern je: 0
KW restrict je: 0
KW unsigned je: 1
KW char je: 5
KW float je: 0
KW return je: 30
KW void je: 8
KW _Complex je: 0
KW for je: 1
KW short je: 0
KW volatile je: 0
KW const je: 0
KW goto je: 0
KW signed je: 0
KW while je: 15
KW continue je: 0
KW if je: 70
KW sizeof je: 5
KW default je: 0
KW _Imaginary je: 0
KW static je: 0
KW do je: 0
KW inline je: 0
KW struct je: 11
int(252)
